baseURL: "https://jhz1127.github.io/CS_Blog/"
title: "大米粥的技术博客"
# pagination:
#   pagerSize: 5
theme: PaperMod

# Set the publish directory
publishDir: "public"

# Add this line to specify the theme properly
themesDir: "themes"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Add language settings
languageCode: "zh-cn"
defaultContentLanguage: "zh-cn"

languages:
  zh-cn:
    languageName: "中文"
    weight: 1

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: "我的技术博客"
  description: "分享技术心得与学习笔记"
  keywords: [Blog, Portfolio, PaperMod]
  author: "大米粥"
  DateFormat: "2006-01-02"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: false

  profileMode:
    enabled: true
    title: "我的技术博客"
    subtitle: "分享技术心得与学习笔记"
    imageUrl: "https://jhz1127.github.io/CS_Blog/imgs/avatar.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: MyAvatar
    buttons:
      - name: 文章
        url: posts
      - name: 标签
        url: tags

  socialIcons:
    - name: github
      url: "https://github.com/yourusername"

menu:
  main:
    - identifier: categories
      name: 分类
      url: /categories/
      weight: 10
    - identifier: tags
      name: 标签
      url: /tags/
      weight: 20
    - identifier: archives
      name: 归档
      url: /archives/
      weight: 30